"""Uniq tag

Revision ID: 3831452d5147
Revises: 16fe1ed6b8ad
Create Date: 2024-11-14 19:50:45.361111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3831452d5147'
down_revision: Union[str, None] = '16fe1ed6b8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_tag', 'tags', ['tag_name', 'tag_color'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_tag', 'tags', type_='unique')
    # ### end Alembic commands ###
